# Generated by Django 2.2 on 2018-11-16 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学校名字')),
                ('address', models.CharField(max_length=100, verbose_name='学校地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(choices=[('1', '对公金融'), ('2', '保险系统'), ('3', '养成快现')], max_length=50, verbose_name='项目名')),
                ('primary_requirement', models.CharField(max_length=100, verbose_name='主要需求')),
                ('special_requirement', models.CharField(max_length=200, verbose_name='具体需求')),
                ('renew_starttime', models.DateField(blank=True, null=True, verbose_name='需求评审时间')),
                ('plan_testtime', models.DateField(blank=True, null=True, verbose_name='计划提测时间')),
                ('fact_testtime', models.DateField(blank=True, null=True, verbose_name='实际提测时间')),
                ('plan_goline_time', models.DateField(blank=True, null=True, verbose_name='计划上线时间')),
                ('fact_goline_time', models.DateField(blank=True, null=True, verbose_name='实际上线时间')),
                ('tester_num', models.IntegerField(default=0, verbose_name='测试人力')),
                ('bug_num', models.IntegerField(blank=True, null=True, verbose_name='bug数')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目版本计划',
                'verbose_name_plural': '项目版本计划',
            },
        ),
    ]
