# Generated by Django 2.2 on 2018-11-15 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(choices=[('1', '金融中心'), ('2', '优信二手车'), ('3', '优信拍')], max_length=50, verbose_name='部门')),
                ('pro_stype', models.CharField(max_length=100, verbose_name='项目名')),
                ('story_num', models.IntegerField(default=0, verbose_name='上线需求')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
    ]
