# Generated by Django 2.2 on 2018-11-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_program_depart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
